### ISSUE TITLE
[FEA] splitK support for Gemv kernel

### ISSUE THREAD

**Issue by ZhangGe6** [NVIDIA/cutlass#909] opened 2023-04-06 13:15 UTC
## Is your feature request related to a problem? Please describe.
I implemented a Gemv kernel `y = Ax` using cutlass, where the shape of `A` is `(5, 2048)` and the shape of `x` is `(2048, 1)`. However, it seems that the performance is far from satisfying.

Here is my minimal Gemv kernel implementation using cutlass. 
```cu
#include <iostream>

#include "cutlass/cutlass.h"
#include "cutlass/gemm/device/gemm.h"
#include "cutlass/gemm/device/gemv.h"
#include "cutlass/gemm/kernel/gemv.h"
#include "cutlass/gemm/device/gemm_universal.h"

#include "cutlass/util/command_line.h"
#include "cutlass/util/host_tensor.h"
#include "cutlass/util/reference/device/gemm.h"
#include "cutlass/util/reference/host/tensor_compare.h"
#include "cutlass/util/reference/host/tensor_copy.h"
#include "cutlass/util/reference/host/tensor_fill.h"
#include "cutlass/util/tensor_view_io.h"
#include "cutlass/util/reference/host/tensor_fill.h"
#include "cutlass/util/reference/host/tensor_copy.h"
#include "cutlass/util/reference/host/tensor_compare.h"
#include "cutlass/util/reference/host/tensor_norm.h"
#include "cutlass/util/reference/host/gemm.h"
#include "cutlass/util/reference/host/gemm_complex.h"

#define CUTLASS_CHECK(status)                                                         \
  {                                                                                   \
    cutlass::Status error = status;                                                   \
    if (error != cutlass::Status::kSuccess) {                                         \
      auto msg = std::string("[") + __FILE__ + "] Got cutlass error: " +              \
          cutlassGetStatusString(error) + " at: " + std::to_string(__LINE__);         \
      std::cerr << msg << std::endl;                                                  \
      throw std::runtime_error(msg);                                                  \
    }                                                                                 \
  }

using ElementAccumulator = float;
using ElementA = float;
using ElementB = float;
using ElementC = float;

using LayoutA = cutlass::layout::ColumnMajor;
using LayoutV = cutlass::layout::RowMajor;

using EpilogueOp = cutlass::epilogue::thread::LinearCombination<
    ElementC,
    1,
    ElementAccumulator, 
    ElementAccumulator>;

using DeviceGemvInstance = cutlass::gemm::device::Gemv<
    cutlass::gemm::kernel::Gemv<
        ElementA,
        LayoutA,
        ElementB,
        ElementC,
        ElementAccumulator,
        EpilogueOp
        >
    >;
using ElementCompute = typename DeviceGemvInstance::EpilogueOutputOp::ElementCompute;

int main(int argc, char** argv) {

    int batch = std::stoi(argv[1]);
    int m = std::stoi(argv[2]);
    int k = std::stoi(argv[3]);

    ElementCompute alpha = ElementCompute(1);
    ElementCompute beta = ElementCompute(0);

    uint8_t* global_workspace = nullptr;
    cudaStream_t stream = nullptr;

    cutlass::HostTensor<ElementA, LayoutA> tensor_A;
    cutlass::HostTensor<ElementB, LayoutV> tensor_B;
    cutlass::HostTensor<ElementC, LayoutV> tensor_C;
    cutlass::HostTensor<ElementC, LayoutV> tensor_D;

    tensor_A.resize({m, k});
    tensor_B.resize({k, 1});
    tensor_C.resize({m, 1});
    tensor_D.resize({m, 1});

    cutlass::reference::host::TensorFillRandomUniform(
        tensor_A.host_view(), 
        1,  // seed
        7,  // scope_max
        -8, // scope_min
        0);
    cutlass::reference::host::TensorFillRandomUniform(
        tensor_B.host_view(), 
        1,  // seed
        7,  // scope_max
        -8, // scope_min
        0);
    cutlass::reference::host::TensorFillRandomUniform(
        tensor_C.host_view(), 
        1,  // seed
        7,  // scope_max
        -8, // scope_min
        0);
    cutlass::reference::host::TensorFill(
        tensor_D.host_view());
    
    tensor_A.sync_device();
    tensor_B.sync_device();
    tensor_C.sync_device();
    tensor_D.sync_device();

    typename DeviceGemvInstance::Arguments arguments{
      {m, k},
      {alpha, beta},
      tensor_A.device_ref(),
      tensor_B.device_data(),
      tensor_C.device_data(),
      tensor_D.device_data(),
      tensor_B.layout().stride(0),
      tensor_C.layout().stride(0),
      tensor_D.layout().stride(0)
    };

    DeviceGemvInstance gemm_op;
    size_t workspace_size = DeviceGemvInstance::get_workspace_size(arguments);
    cutlass::device_memory::allocation<uint8_t> local_workspace(workspace_size);
    global_workspace = local_workspace.get();
    
    cutlass::Status status;
    status = gemm_op.can_implement(arguments);
    CUTLASS_CHECK(status);

    status = gemm_op.initialize(arguments, global_workspace);
    CUTLASS_CHECK(status);

    // warmup
    status = gemm_op(stream);
    CUTLASS_CHECK(status);

    cudaEvent_t events[2];
    for (auto & event : events) {
        cudaEventCreate(&event);
    }
    cudaEventRecord(events[0]);
    for (int iter = 0; iter < 5; ++iter) {
        status = gemm_op();
        CUTLASS_CHECK(status);
    }
    cudaEventRecord(events[1]);
    cudaEventSynchronize(events[1]);

    float runtime_ms = 0.0f;
    cudaEventElapsedTime(&runtime_ms, events[0], events[1]);
    for (auto event : events) {
        (void)cudaEventDestroy(event);
    }

    if (runtime_ms < 0.00001) {
      throw std::runtime_error("OOB in cutlass.");
    }

    runtime_ms = runtime_ms / 5;
    std::cout << "RUNTIME MS:" << runtime_ms << std::endl;
}
```
Compile the code using
```sh
cutlass_root_path=path/to/cutlass

code_file_path="./gemv.cu"
exe_path="./gemv.out"

nvcc --std=c++17 -arch=compute_80 -code=sm_80 -I$cutlass_root_path/include -I$cutlass_root_path/tools/util/include -I$cutlass_root_path/examples/common -I$cutlass_root_path/test --compiler-options '-fPIC' -O3 $code_file_path -o $exe_path
```
Run
```sh
./gemv.out 1 5 2048
```
Then I got
```sh
RUNTIME MS: 0.595149
```
I also implemented a Gemm kernel using `GemmUniversal` and got 
```sh
RUNTIME MS: 0.016421
```
So it seems that the performance of `Gemv` kernel has a huge room to improve.

## Describe the solution you'd like

**Adding `splitK` support for `Gemv` kernel may help.** This is based on my two observations:
1. **The performance of `Gemv` drops "dramatically" as K increases.** Based on the above code, I set `m = 5` and `k` to some different values and got the profile values as follows:

|  k  | 32 | 64 | 256  | 512 | 1024 | 2048  |
|  ----  | ----  | ----  | ----  | ----  | ----  | ----  |
| **Run time / ms**  | 0.01 | 0.02 | 0.06 | 0.12 |  0.24  | 0.59  |

2. splitK helps improve the performance of `Gemm` kernel effectively. I conducted some experiments based on `cutlass/examples/06_splitK_gemm/splitk_gemm.cu`. I set `m = 128, n = 128` and `k = 4096`. By setting `split_k_slices` to various values, I got the profile results as follows:

|  split_k_slices  | 1 | 4 | 8  | 16 | 32 | 64  |
|  ----  | ----  | ----  | ----  | ----  | ----  | ----  |
| **Run time / ms**  | 11.88 | 3.02 | 1.51 | 0.76 |  0.39  | 0.20  |

## Describe alternatives you've considered
Besides `Gemv`, I also found a Gemv class `DefaultGemv`. But it seems `DefaultGemv` doesn't support splitK either, and the performance under big `k` dimension is not satisfying, too.

**Comment by hwu36** [comment] 2023-04-06 14:18
splitk is not hard to implement.

first, grid.z needs to be set as the slice number

second, adjust problem size in the k dimension like https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L499

third, set the correct pointer to point to the new beginning like https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L515

forth, fetch and wait for the semaphore like https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L607 and https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L659

fifth, reduce the different k slices

sixth, release the semaphore https://github.com/NVIDIA/cutlass/blob/master/include/cutlass/gemm/kernel/gemm_universal.h#L687

above is serial splitk, we can talk about parallel splitk after serial is working.

**Comment by bitxsw93** [comment] 2023-04-10 07:23
I met the same question.
So Gemv kernel is much slower than Gemm Kernel. how to handle this?

**Comment by hwu36** [comment] 2023-04-11 03:52
see my reply above.  you need to add splitk on top of it.

**Comment by NVJiangShao** [comment] 2023-05-26 08:24
@ZhangGe6 @bitxsw93 @hwu36 

Update to CUTLASS 3.1 and try the new gemv with `LayoutA = cutlass::layout::RowMajor`, which needs a row-major input matrix. This kernel is fine-tuned and newly added in CUTLASS 3.1.

If a column-major input matrix is inevitable, you may need to wait for next CUTLASS release.

For the case @ZhangGe6 gives above, the results on a 3090 are listed below.

CUDA 12.0
Driver Version: 525.105.17

In this case, you need to set `kElementsPerAccess_ = 4`, `kThreadCount_ = 128` and `kThreadsPerRow_ = 128`.

| Problem Size | original column-major input matrix gemv in CUTLASS | cuBLAS | new row-major input matrix gemv in CUTLASS |
| :----: | :----: | :----: | :----: |
| b1_m5_k2048 | 238.273 us | 4.745 us | 2.531 us |

Hope you enjoy this new implementation. :blush:

**Comment by hwu36** [comment] 2023-05-26 13:10
i think i squeezed your col major into 3.1

**Comment by NVJiangShao** [comment] 2023-05-26 16:13
> i think i squeezed your col major into 3.1

I did nothing to the original col-major gemv. Just added a row-major one into gemv.h, which can be used whether the problem is strided batched gemv or just a single gemv.
The optimization of col-major gemv will be my next step.

**Comment by ZhangGe6** [comment] 2023-05-28 04:05
@NVJiangShao Good Job! 🎉 🎉 🎉

**Comment by mnicely** [comment] 2023-05-30 20:22
I think we can close this now. Reopen if needed.

**Closed by mnicely** 2023-05-30 20:22 UTC
Labels: feature request, help wanted, good first issue
