### ISSUE TITLE
ldmatrix instruction

### ISSUE THREAD

**Issue by LANSHANGH** [NVIDIA/cutlass#1628] opened 2024-07-12 09:35 UTC
**Is your feature request related to a problem? Please describe.**
About the ldmatrix instruction called by the SM75_U16x4_LDSM_T method in the copy_sm75.hpp file

**Describe the solution you'd like**
I'm curious why not every thread in warp accesses consecutive 16*16 matrix fragments, because then every thread in warp can also use efficient store instructions such as store.v4 when accessing shared memory after the computation is done.

**Describe alternatives you've considered**
I am curious why the PTX documentation describes that when the ldmatrix instruction is called to read four 8*8 matrices, the matrix fragment held by each thread in a warp is not a continuous matrix fragment, but a fragment of an 8*8 matrix accessed by each thread instead of a continuous fragment of a 16*16 matrix accessed by each thread.

**Additional context**
Regarding the ldmatrix instruction called by the SM75_U16x4_LDSM_T method in copy_sm75.hpp file, I am curious why the PTX documentation describes that when calling the ldmatrix instruction to read four 8*8 matrices, The matrix fragment held by each thread in a warp is not a continuous matrix fragment, but a fragment of an 8*8 matrix accessed by each thread, rather than a continuous fragment of a 16*16 matrix accessed by each thread. I wonder why not every thread in warp accesses a continuous 16*16 matrix fragment, because then, Each thread in warp can also use efficient store instructions, such as store.v4, when accessing shared memory after the calculation is complete. Can you answer this question for me

**Comment by thakkarV** [comment] 2024-07-15 15:57
duplicate of  https://github.com/NVIDIA/cutlass/issues/1635

**Closed by thakkarV** 2024-07-15 15:57 UTC
Labels: feature request, ? - Needs Triage
