### ISSUE TITLE
CutClass failed when build with permissive- + MSVC on windows.

### ISSUE THREAD

**Issue by QuellaZhang** [NVIDIA/cutlass#27] opened 2018-09-26 02:02 UTC
CutClass failed with error C3861 when build with permissive- on Windows, I use latest source on master branch. Could you please help take a look at this? 
**You can repro this issue as the steps below:**

1. git clone https://github.com/NVIDIA/cutlass d:\Cutclass\src
2. open a clean x64 prompt and browse to D:\CutClass
3. mkdir build_x64 && pushd build_x64
4. set _CL_=/permissive-
5. cmake -G "Visual Studio 15 2017 Win64" -DCMAKE_SYSTEM_VERSION=10.0.17134.0 -DCUTLASS_NVCC_ARCHS=70 ..\src\
6. msbuild /p:Configuration=Release;Platform=x64 CUTLASS.sln /t:Rebuild

**Error info:**
D:\cutclass\src\cutlass/gemm/wmma_gemm_global_tile.h(108): error C3861: 'stride_d': identifier not found [D:\cutclass\build_x64\tools\test\unit\cutlass_unit_test.vcxproj]
  D:\cutclass\src\cutlass/gemm/wmma_gemm_global_tile.h(162): note: see reference to class template instantiation 'cutlass::gemm::WmmaGemmGlobalIteratorCd<TileTraits_,Index_>' being compiled
D:\cutclass\src\cutlass/gemm/wmma_gemm_global_tile.h(110): error C3861: 'stride_h': identifier not found [D:\cutclass\build_x64\tools\test\unit\cutlass_unit_test.vcxproj]
D:\cutclass\src\cutlass/gemm/wmma_gemm_global_tile.h(112): error C3861: 'inc_h': identifier not found [D:\cutclass\build_x64\tools\test\unit\cutlass_unit_test.vcxproj]
D:\cutclass\src\cutlass/gemm/wmma_gemm_global_tile.h(113): error C3861: 'inc_advance': identifier not found [D:\cutclass\build_x64\tools\test\unit\cutlass_unit_test.vcxproj]
D:\cutclass\src\cutlass/gemm/wmma_gemm_global_tile.h(113): error C3861: 'inc_h': identifier not found [D:\cutclass\build_x64\tools\test\unit\cutlass_unit_test.vcxproj]
D:\cutclass\src\cutlass/gemm/wmma_gemm_global_tile.h(115): error C3861: 'predicate_offset': identifier not found [D:\cutclass\build_x64\tools\test\unit\cutlass_unit_test.vcxproj]
D:\cutclass\src\cutlass/gemm/wmma_gemm_global_tile.h(116): error C3861: 'predicate_inc_h': identifier not found [D:\cutclass\build_x64\tools\test\unit\cutlass_unit_test.vcxproj]
D:\cutclass\src\cutlass/gemm/wmma_gemm_global_tile.h(117): error C3861: 'predicate_inc_advance': identifier not found [D:\cutclass\build_x64\tools\test\unit\cutlass_unit_test.vcxproj]
D:\cutclass\src\cutlass/gemm/wmma_gemm_global_tile.h(117): error C3861: 'predicate_inc_h': identifier not found [D:\cutclass\build_x64\tools\test\unit\cutlass_unit_test.vcxproj]

**Comment by QuellaZhang** [comment] 2018-09-27 01:56
This issue can be reproduecd on latest VS version. You can download the update VS from here: https://visualstudio.microsoft.com/vs/

**Comment by kerrmudgeon** [comment] 2018-09-27 19:59
Thank you for noting this. We will take a look and try to resolve the issue.

**Comment by QuellaZhang** [comment] 2018-10-10 08:48
Hello, any updates here?

**Comment by kerrmudgeon** [comment] 2018-10-26 17:31
I was able to build with `/permissive-` without problems on Visual Studio 2017.

Given the nature of your error messages, I wonder if the issue is related to CUDA Toolkit version. Can you list the version of CUDA you're using?
```
$ nvcc --version                                                                          
nvcc: NVIDIA (R) Cuda compiler driver                                                                                                       Copyright (c) 2005-2018 NVIDIA Corporation                                                                                                  Built on Sat_Aug_25_21:08:04_Central_Daylight_Time_2018                                                                                     Cuda compilation tools, release 10.0, V10.0.130  
```

**Comment by kerrmudgeon** [comment] 2018-10-26 22:01
Hello. I was able to reproduce the problem (in spite of my earlier message to the contrary, which I hastily removed) with Visual Studio 2017.

We've updated the code to fix the issue with compiling with `/permissive-`. Can you try out CUTLASS 1.2 and see if the problem has been resolved?

**Comment by QuellaZhang** [comment] 2018-10-29 08:53
@kerrmudgeon Thank you very much! : )
Verfied this issue has gone in latest version. Cutclass works well now under /permissive- mode.

**Comment by kerrmudgeon** [comment] 2018-10-29 15:38
Thanks! Closing.

**Closed by kerrmudgeon** 2018-10-29 15:38 UTC
