### ISSUE TITLE
Is there missing a 'divice_memory::' before 'copy_device_to_device'

### ISSUE THREAD

**Issue by zheng95z** [NVIDIA/cutlass#250] opened 2021-04-25 11:59 UTC
https://github.com/NVIDIA/cutlass/blob/8f09b82b12cbea6943d54fd4f66c0a769b719f58/tools/util/include/cutlass/util/device_memory.h#L266

**Comment by hwu36** [comment] 2021-04-26 02:09
Yes, this is a duplicate of #205

**Closed** 2021-04-26 15:50 UTC
