### ISSUE TITLE
[BUG] CUTE: zipped_divide function returns different results on cuda device and on host

### ISSUE THREAD

**Issue by Muxas** [NVIDIA/cutlass#1580] opened 2024-06-09 12:59 UTC
**Describe the bug**
if a shape and a stride of a tensor are not of depth 1, then zipped_divide results in different results on CUDA and HOST devices.

**Steps/Code to reproduce bug**
Minimal working example contains only 40 lines of code: https://gist.github.com/Muxas/07bb3019183d516759d7d63b5ee1c8c1

**Expected behavior**
Results must be equal no matter which device is used.

**Environment details (please complete the following information):**
Nvidia A100 device

**Comment by ccecka** [comment] 2024-06-09 15:47
I tested this on an A100 and a TITAN V and can't reproduce it.
```
scratch$ nvidia-smi
Sun Jun  9 08:39:14 2024       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 550.54.14              Driver Version: 550.54.14      CUDA Version: 12.4     |
|-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  NVIDIA A100 80GB PCIe          On  |   00000000:01:00.0 Off |                    0 |
| N/A   31C    P0             40W /  300W |       0MiB /  81920MiB |      0%      Default |
|                                         |                        |             Disabled |
+-----------------------------------------+------------------------+----------------------+
                                                                                         
+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI        PID   Type   Process name                              GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+
scratch$ make scratch_bug
nvcc  -ccbin=g++ -O3 -std=c++17 -ftemplate-backtrace-limit=0 -arch sm_80 --expt-extended-lambda --expt-relaxed-constexpr --use_fast_math -Xptxas -v --compiler-options "-O3 -std=c++17 -ftemplate-backtrace-limit=0 -Wall -Wno-unused-local-typedefs -Wno-strict-aliasing -Wno-unused-function -Wno-format-security -Wno-unknown-pragmas -Wno-psabi" -I. -I/home/cuda/include -I/home/cutlass/include -I/home/cutlass/tools/util/include -I/home/cutlass/test -I/home/cutlass/examples -o scratch_bug scratch_bug.cu -L/home/lib64 
ptxas info    : 17 bytes gmem, 72 bytes cmem[4]
ptxas info    : Compiling entry function '_Z11test_devicev' for 'sm_80'
ptxas info    : Function properties for _Z11test_devicev
    8 bytes stack frame, 0 bytes spill stores, 0 bytes spill loads
ptxas info    : Used 24 registers, 8 bytes cumulative stack size, 352 bytes cmem[0]
scratch$ ./scratch_bug 
host:
(1,(8,8))
(1,(1,64))
(1,(8,8)):(1,(1,64))
(1,8)
(0,_)
((1,(8,1)),(1,(1,8))):((1,(1,64)),(1,(8,64)))
device:
(1,(8,8))
(1,(1,64))
(1,(8,8)):(1,(1,64))
(1,8)
(0,_)
((1,(8,1)),(1,(1,8))):((1,(1,64)),(1,(8,64)))
```
Can you provide more information about your compiler, build environment, and output that you are receiving?

**Comment by Muxas** [comment] 2024-06-09 16:43
Here are `nvidia-smi`, compilation and output:
```
(mikhalev) ➜  gemm nvidia-smi
Sun Jun  9 19:41:53 2024       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 450.172.01   Driver Version: 450.172.01   CUDA Version: 12.3     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  A100 80GB PCIe      Off  | 00000000:5E:00.0 Off |                    0 |
| N/A   34C    P0    44W / 300W |      0MiB / 81252MiB |      0%      Default |
|                               |                      |             Disabled |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
(mikhalev) ➜  gemm nvcc zip.cu -Icutlass/include/ -Icutlass/tools/util/include --std=c++17 -O3 --gpu-code=sm_80 --gpu-architecture=compute_80 -Icutlass/examples/common -o zip        
cutlass/include/cute/container/tuple.hpp(129): warning #20013-D: calling a constexpr __host__ function("move") from a __host__ __device__ function("getv") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
  { return cute::move(x.t_); }
           ^
          detected during:
            instantiation of "T &&cute::detail::getv(cute::detail::EBO<N, T, false> &&) [with N=0UL, T=int]" at line 1124 of cutlass/include/cute/layout.hpp
            instantiation of "auto cute::detail::complement(const Shape &, const Stride &, const CoTarget &) [with Shape=int, Stride=cute::C<1>, CoTarget=int]" at line 1152 of cutlass/include/cute/layout.hpp
            instantiation of "auto cute::complement(const cute::Layout<Shape, Stride> &, const CoTarget &) [with Shape=int, Stride=cute::_1, CoTarget=int]" at line 1426 of cutlass/include/cute/layout.hpp
            instantiation of "auto cute::logical_divide(const cute::Layout<LShape, LStride> &, const cute::Layout<TShape, TStride> &) [with LShape=int, LStride=int, TShape=int, TStride=cute::_1]" at line 1441 of cutlass/include/cute/layout.hpp
            instantiation of "auto cute::logical_divide(const cute::Layout<LShape, LStride> &, const Tiler &) [with LShape=int, LStride=int, Tiler=int]" at line 1437 of cutlass/include/cute/layout.hpp
            instantiation of function "lambda [](const auto &, const auto &)->auto [with <auto-1>=cute::Layout<int, int>, <auto-2>=int]" at line 704 of cutlass/include/cute/layout.hpp
            instantiation of "auto cute::detail::transform_layout(const Tuple0 &, const Tuple1 &, F &&, cute::seq<I...>, cute::seq<I0...>, cute::seq<I1...>) [with Tuple0=cute::Layout<cute::tuple<int, cute::tuple<int, int>>, cute::tuple<int, cute::tuple<int, int>>>, Tuple1=cute::tuple<int, int>, F=lambda [](const auto &, const auto &)->auto &, I=<0, 1>, I0=<>, I1=<>]" at line 725 of cutlass/include/cute/layout.hpp
            instantiation of "auto cute::transform_layout(const Tuple0 &, const Tuple1 &, F &&) [with Tuple0=cute::Layout<cute::tuple<int, cute::tuple<int, int>>, cute::tuple<int, cute::tuple<int, int>>>, Tuple1=cute::tuple<int, int>, F=lambda [](const auto &, const auto &)->auto]" at line 1437 of cutlass/include/cute/layout.hpp
            instantiation of "auto cute::logical_divide(const cute::Layout<LShape, LStride> &, const Tiler &) [with LShape=cute::tuple<int, cute::tuple<int, int>>, LStride=cute::tuple<int, cute::tuple<int, int>>, Tiler=cute::tuple<int, int>]" at line 1477 of cutlass/include/cute/layout.hpp
            instantiation of "auto cute::zipped_divide(const cute::Layout<LShape, LStride> &, const Tiler &) [with LShape=cute::tuple<int, cute::tuple<int, int>>, LStride=cute::tuple<int, cute::tuple<int, int>>, Tiler=cute::tuple<int, int>]" at line 19 of zip.cu

Remark: The warnings can be suppressed with "-diag-suppress <warning-number>"

cutlass/include/cute/container/tuple.hpp(129): warning #20013-D: calling a constexpr __host__ function("move") from a __host__ __device__ function("getv") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
  { return cute::move(x.t_); }
           ^
          detected during instantiation of "T &&cute::detail::getv(cute::detail::EBO<N, T, false> &&) [with N=1UL, T=int]" at line 19 of zip.cu

cutlass/include/cute/container/tuple.hpp(129): warning #20015-D: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
  { return cute::move(x.t_); }
    ^

cutlass/include/cute/container/tuple.hpp(129): warning #20015-D: calling a constexpr __host__ function from a __host__ __device__ function is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.
  { return cute::move(x.t_); }
    ^

cutlass/include/cute/container/tuple.hpp(129): warning #20013-D: calling a constexpr __host__ function("std::remove_reference<T1> ::type && cute::move<int &> (T1 &&)") from a __host__ __device__ function("cute::detail::getv<(unsigned long)0ul, int> ") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

cutlass/include/cute/container/tuple.hpp(129): warning #20013-D: calling a constexpr __host__ function("std::remove_reference<T1> ::type && cute::move<int &> (T1 &&)") from a __host__ __device__ function("cute::detail::getv<(unsigned long)1ul, int> ") is not allowed. The experimental flag '--expt-relaxed-constexpr' can be used to allow this.

(mikhalev) ➜  gemm ./zip           
host:
(1,(8,8))
(1,(1,64))
(1,(8,8)):(1,(1,64))
(1,8)
(0,_)
((1,(8,1)),(1,(1,8))):((1,(1,64)),(1,(8,64)))
device:
(1,(8,8))
(1,(1,64))
(1,(8,8)):(1,(1,64))
(1,8)
(0,_)
((1,(8,1)),(0,(0,0))):((1,(1,64)),(0,(0,0)))
(mikhalev) ➜  gemm 
```
and `nvcc` version:
```
(mikhalev) ➜  gemm nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2024 NVIDIA Corporation
Built on Tue_Feb_27_16:19:38_PST_2024
Cuda compilation tools, release 12.4, V12.4.99
Build cuda_12.4.r12.4/compiler.33961263_0
```

**Comment by Muxas** [comment] 2024-06-09 16:59
switching `nvcc` from 12.4 to 12.3 and providing all the same compilation flags from your test run solved the problem. However, with flags, limited to
```
(mikhalev) ➜  gemm nvcc zip.cu -Icutlass/include/ -Icutlass/tools/util/include --std=c++17 -O3 --gpu-code=sm_80 --gpu-architecture=compute_80 -Icutlass/examples/common -o zip
```
the error is still there for downgraded `nvcc`.

**Comment by thakkarV** [comment] 2024-06-09 17:05
You're missing the relaxed constexpr flag to NVCC I think. Are you sure you're using the same set of flags that cutlass cmake spits out?

**Comment by Muxas** [comment] 2024-06-09 17:06
Further digging showed, that it is the flag `--expt-relaxed-constexpr` that makes the test work correctly. Output was so long, that I did not read it properly. I mean it is just a warning, not an error -- I was not forced to read it carefully.

**Comment by thakkarV** [comment] 2024-06-09 17:35
Note, CUTLASS doesn't support compilation with command line flags that aren't generated by our build system. Closing as NAB

**Closed** 2024-06-09 17:35 UTC
Labels: bug, ? - Needs Triage
